## Project : Next Word Prediction Using LSTM

#### Project Overview 

- 1. Data Collection : Shakespeare "Hamlet" this is our dataset
- 2. Data Preprocessing 
- 3. Model Building
- 4. Model Training
- 5. Model Evaluation / Prediction
- 6. Deployment

In [25]:
import nltk

In [26]:
## Data Collection

nltk.download('gutenberg')

from nltk.corpus import gutenberg
import pandas as pd

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\digit\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [27]:
data = gutenberg.raw('shakespeare-caesar.txt')

with open('julius_caesar.txt','w') as file:
    file.write(data)



In [28]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

In [29]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
with open('julius_caesar.txt','r') as file:
    text=file.read().lower()


tokenizer = Tokenizer()

tokenizer.fit_on_texts([text])

total_words= len(tokenizer.word_index)+1

total_words



3086

In [32]:
tokenizer.word_index

{'and': 1,
 'the': 2,
 'i': 3,
 'to': 4,
 'you': 5,
 'of': 6,
 'that': 7,
 'a': 8,
 'not': 9,
 'is': 10,
 'in': 11,
 'my': 12,
 'it': 13,
 'caesar': 14,
 'me': 15,
 'he': 16,
 'for': 17,
 'this': 18,
 'him': 19,
 'will': 20,
 'brutus': 21,
 'his': 22,
 'bru': 23,
 'with': 24,
 'your': 25,
 'be': 26,
 'haue': 27,
 'but': 28,
 'so': 29,
 'as': 30,
 'what': 31,
 'shall': 32,
 'do': 33,
 'thou': 34,
 'are': 35,
 'all': 36,
 'then': 37,
 'cassi': 38,
 'by': 39,
 'we': 40,
 'no': 41,
 'our': 42,
 'cassius': 43,
 'if': 44,
 'on': 45,
 'antony': 46,
 'come': 47,
 'did': 48,
 'good': 49,
 'men': 50,
 'o': 51,
 'know': 52,
 'when': 53,
 'they': 54,
 'was': 55,
 'enter': 56,
 'let': 57,
 'now': 58,
 'vs': 59,
 'their': 60,
 'them': 61,
 'man': 62,
 'at': 63,
 'am': 64,
 'thy': 65,
 'heere': 66,
 'thee': 67,
 'from': 68,
 'there': 69,
 'ant': 70,
 'well': 71,
 'vpon': 72,
 'which': 73,
 'day': 74,
 'would': 75,
 'lord': 76,
 'or': 77,
 'why': 78,
 'yet': 79,
 'night': 80,
 'go': 81,
 'some': 82,
 

In [33]:
input_sequences = []

for line in text.split('\n'):
    token_list= tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)
    

In [34]:
input_sequences

[[2, 896],
 [2, 896, 6],
 [2, 896, 6, 1381],
 [2, 896, 6, 1381, 14],
 [2, 896, 6, 1381, 14, 39],
 [2, 896, 6, 1381, 14, 39, 1382],
 [2, 896, 6, 1381, 14, 39, 1382, 1383],
 [2, 896, 6, 1381, 14, 39, 1382, 1383, 1384],
 [476, 1385],
 [476, 1385, 1386],
 [476, 1385, 1386, 1387],
 [56, 477],
 [56, 477, 897],
 [56, 477, 897, 1],
 [56, 477, 897, 1, 400],
 [56, 477, 897, 1, 400, 898],
 [56, 477, 897, 1, 400, 898, 301],
 [56, 477, 897, 1, 400, 898, 301, 2],
 [56, 477, 897, 1, 400, 898, 301, 2, 1388],
 [477, 235],
 [477, 235, 236],
 [477, 235, 236, 5],
 [477, 235, 236, 5, 700],
 [477, 235, 236, 5, 700, 899],
 [477, 235, 236, 5, 700, 899, 253],
 [477, 235, 236, 5, 700, 899, 253, 5],
 [477, 235, 236, 5, 700, 899, 253, 5, 236],
 [10, 18],
 [10, 18, 8],
 [10, 18, 8, 1389],
 [10, 18, 8, 1389, 31],
 [10, 18, 8, 1389, 31, 52],
 [10, 18, 8, 1389, 31, 52, 5],
 [10, 18, 8, 1389, 31, 52, 5, 9],
 [274, 1390],
 [274, 1390, 5],
 [274, 1390, 5, 558],
 [274, 1390, 5, 558, 9],
 [274, 1390, 5, 558, 9, 362],
 [72

In [35]:
max_sequence_len = max([len(x) for x in input_sequences])


max_sequence_len

14

In [36]:
input_sequences = np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))

input_sequences

array([[   0,    0,    0, ...,    0,    2,  896],
       [   0,    0,    0, ...,    2,  896,    6],
       [   0,    0,    0, ...,  896,    6, 1381],
       ...,
       [   0,    0,    0, ...,    2,  896,    6],
       [   0,    0,    0, ...,  896,    6, 3085],
       [   0,    0,    0, ...,    6, 3085,   14]],
      shape=(17756, 14), dtype=int32)

In [37]:
x,y = input_sequences[:,:-1],input_sequences[:,-1]

In [38]:
x

array([[   0,    0,    0, ...,    0,    0,    2],
       [   0,    0,    0, ...,    0,    2,  896],
       [   0,    0,    0, ...,    2,  896,    6],
       ...,
       [   0,    0,    0, ..., 3084,    2,  896],
       [   0,    0,    0, ...,    2,  896,    6],
       [   0,    0,    0, ...,  896,    6, 3085]],
      shape=(17756, 13), dtype=int32)

In [39]:
y

array([ 896,    6, 1381, ...,    6, 3085,   14],
      shape=(17756,), dtype=int32)

In [40]:
import tensorflow as tf
y = tf.keras.utils.to_categorical(y,num_classes=total_words)

y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(17756, 3086))

In [41]:
## split the data into training and testing sets

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [42]:
## Define early stopping method

from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss',patience=3, restore_best_weights=True)

In [43]:
## Build the model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout


# Define the model
#model = Sequential()
#model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model = Sequential()
model.add(tf.keras.Input(shape=(max_sequence_len - 1,), dtype="int32"))
model.add(Embedding(input_dim=total_words, output_dim=100))

model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.20))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 13, 100)        │       308,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 13, 150)        │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 13, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 100)            │       100,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3086)           │       311,686 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 871,286 (3.32 MB)

 Trainable params: 871,286 (3.32 MB)

 Non-trainable params: 0 (0.00 B)

In [44]:
## Build the model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,GRU,Dense,Dropout


# Define the model
#model = Sequential()
#model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model = Sequential()
model.add(tf.keras.Input(shape=(max_sequence_len - 1,), dtype="int32"))
model.add(Embedding(input_dim=total_words, output_dim=100))

model.add(GRU(150,return_sequences=True))
model.add(Dropout(0.20))
model.add(GRU(100))
model.add(Dense(total_words,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 13, 100)        │       308,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_2 (GRU)                     │ (None, 13, 150)        │       113,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 13, 150)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_3 (GRU)                     │ (None, 100)            │        75,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3086)           │       311,686 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 809,286 (3.09 MB)

 Trainable params: 809,286 (3.09 MB)

 Non-trainable params: 0 (0.00 B)

In [45]:
history = model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),verbose=1,callbacks=[early_stopping])

Epoch 1/50
444/444 ━━━━━━━━━━━━━━━━━━━━ 14s 27ms/step - accuracy: 0.0254 - loss: 6.7417 - val_accuracy: 0.0270 - val_loss: 6.5468
Epoch 2/50
444/444 ━━━━━━━━━━━━━━━━━━━━ 11s 24ms/step - accuracy: 0.0308 - loss: 6.2040 - val_accuracy: 0.0389 - val_loss: 6.6585
Epoch 3/50
444/444 ━━━━━━━━━━━━━━━━━━━━ 20s 24ms/step - accuracy: 0.0429 - loss: 5.9380 - val_accuracy: 0.0386 - val_loss: 6.7149
Epoch 4/50
444/444 ━━━━━━━━━━━━━━━━━━━━ 11s 25ms/step - accuracy: 0.0522 - loss: 5.6910 - val_accuracy: 0.0453 - val_loss: 6.7471


In [46]:
## function to predict next word

def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]


    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len -1 ):]


    token_list = pad_sequences([token_list], maxlen=max_sequence_len -1, padding='pre')

    predicted = model.predict(token_list, verbose=0)

    predicted_word_index = np.argmax(predicted,axis=1)

    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word

    return None

In [47]:
input_text = "yet heare me speake All"

print(f"Input Text: {input_text}")

max_sequence_len = model.input_shape[1]+1

next_word = predict_next_word(model,tokenizer,input_text,max_sequence_len)

print(f"Next Word Prediction: {next_word}")

Input Text: yet heare me speake All
Next Word Prediction: i


In [ ]:
model.save("Next_Word_GRU.h5")

import pickle
with open("tokenizer.pickle",'wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)